stages:
  - deploy

pages:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  image:
    name: node:16
  cache:
    paths:
      - .cache/
  script:
    - npm install && npm run build
  artifacts:
    paths:
      - public/
